### PR TITLE
feature: Added initial support for custom email subjects for GitHub d…

### PR DESCRIPTION
**Pull request by chrisdutz**
…iscussions

### CODE REVIEW

**Comment by Humbedooh** [comment]
Can you put the x1 paths back into the code please? I can then merge and test this

**Comment by chrisdutz** [comment]
What do you mean with 1x path?

**Comment by chrisdutz** [comment]
Oh... Forget it 😉

**Comment by Humbedooh** [comment]
There should probably be a catchall just for discussions, since the format differs from the PR/issue catchall (specifically, PR/issue variables are not available here). Maybe a catchall_discussions?

**Pull request merged**
